name: samurai-mpi-2-env
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - xtensor>0.25
  - highfive>=3.0
  - zlib # Required by highfive (or hdf5) since highfive 3.3 (or hdf5 2.1). Can be removed when highfive (or hdf5) is fixed.
  - fmt
  - pugixml
  - cli11<2.5
  - pytest
  - h5py
  - libboost-mpi #<1.87 # MPI seems broken with 1.87 with the error : symbol not found in flat namespace '_PyBaseObject_Type'
  - libboost-devel
  - libboost-headers
  - "hdf5=*=mpi_*"
  - mpich
