# -*- coding: utf-8 -*-
"""Configuration file for the Sphinx documentation builder."""
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# Sphinx reads its options from module variables with lowercase names.
# pylint: disable=invalid-name

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import shutil
import sys
import subprocess  # nosec B404: runs the doxygen executable found by shutil.which

from sphinx.util import logging

# -- Project information -----------------------------------------------------

project = "samurai"
author = "samurai team"

# Read version from version.txt
with open(
    os.path.join(os.path.dirname(__file__), "../../version.txt"), encoding="utf-8"
) as version_file:
    full_version = version_file.read().strip()

# The short X.Y version
version = ".".join(full_version.split(".")[:2])
# The full version, including alpha/beta/rc tags
release = full_version

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# Project extensions live in _ext/.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "_ext"))

extensions = [
    "statements",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "breathe",
    "myst_parser",
]

breathe_projects = {"samurai": "../xml"}
breathe_default_project = "samurai"

# Breathe declares the enclosing namespace (`samurai`) once per `doxygenfile`
# directive, and the Sphinx C++ domain reports every declaration after the
# first one as a duplicate. The API pages use `doxygenfile` on several headers
# of the same namespace, so these warnings say nothing about the docs.
suppress_warnings = ["duplicate_declaration.cpp"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# Every page is written in MyST Markdown.
source_suffix = {".md": "markdown"}

# Write `{{ project }}` in a page to get the project name.
myst_substitutions = {"project": project}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []



# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# The name in the browser tab and in the mobile header, after the page title.
html_title = project

# The colours, faces and sizes, Furo's own variables included, live in
# _static/css/samurai.css.
# The GitHub mark of the footer, drawn in the text colour.
GITHUB_ICON = (
    '<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="'
    "M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0"
    "-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1."
    "13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33"
    ".66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-"
    "2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27."
    "68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51"
    ".56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1"
    ".07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.5"
    "8-8-8-8z"
    '"/></svg>'
)

# Furo's own colour and font variables, mapped onto the tokens of samurai.css
# (--sm-*), which hold the light and the dark values; one mapping serves both.
furo_variables = {
    "font-stack": "var(--sm-serif)",
    "font-stack--headings": "var(--sm-serif)",
    "font-stack--monospace": "var(--sm-mono)",
    "color-foreground-primary": "var(--sm-ink)",
    "color-foreground-secondary": "var(--sm-ink-2)",
    "color-foreground-muted": "var(--sm-ink-3)",
    "color-foreground-border": "var(--sm-rule)",
    "color-background-primary": "var(--sm-paper)",
    "color-background-secondary": "var(--sm-side)",
    "color-background-border": "var(--sm-rule)",
    "color-background-hover": "var(--sm-rule-soft)",
    "color-background-hover--transparent": "transparent",
    "color-background-item": "var(--sm-ink-3)",
    "color-brand-primary": "var(--sm-ink)",
    "color-brand-content": "var(--sm-ink)",
    "color-brand-visited": "var(--sm-ink)",
    "color-link": "var(--sm-ink)",
    "color-link--hover": "var(--sm-red)",
    "color-link--visited": "var(--sm-ink)",
    "color-link-underline": "var(--sm-red)",
    "color-link-underline--hover": "var(--sm-red)",
    "color-link-underline--visited": "var(--sm-red)",
    "color-announcement-background": "var(--sm-paper)",
    "color-announcement-text": "var(--sm-ink)",
    "color-header-background": "var(--sm-paper)",
    "color-header-border": "var(--sm-rule)",
    "color-header-text": "var(--sm-ink)",
    "color-sidebar-background": "var(--sm-side)",
    "color-sidebar-background-border": "var(--sm-rule)",
    "color-sidebar-brand-text": "var(--sm-ink)",
    "color-sidebar-caption-text": "var(--sm-ink-2)",
    "color-sidebar-link-text": "var(--sm-ink-2)",
    "color-sidebar-link-text--top-level": "var(--sm-ink-2)",
    "color-sidebar-item-background": "transparent",
    "color-sidebar-item-background--current": "transparent",
    "color-sidebar-item-background--hover": "transparent",
    "color-sidebar-item-expander-background": "transparent",
    "color-sidebar-item-expander-background--hover": "transparent",
    "color-sidebar-search-text": "var(--sm-ink)",
    "color-sidebar-search-background": "var(--sm-paper)",
    "color-sidebar-search-background--focus": "var(--sm-paper)",
    "color-sidebar-search-border": "var(--sm-rule)",
    "color-sidebar-search-icon": "var(--sm-ink-3)",
    "color-toc-background": "var(--sm-paper)",
    "color-toc-title-text": "var(--sm-ink-2)",
    "color-toc-item-text": "var(--sm-ink-2)",
    "color-toc-item-text--hover": "var(--sm-ink)",
    "color-toc-item-text--active": "var(--sm-ink)",
    "color-code-background": "transparent",
    "color-code-foreground": "var(--sm-ink)",
    "color-inline-code-background": "transparent",
    "color-highlighted-background": "var(--sm-red-wash)",
    "color-highlighted-text": "var(--sm-ink)",
    "color-highlight-on-target": "var(--sm-red-wash)",
    "color-admonition-background": "transparent",
    "color-admonition-title-background": "transparent",
    "color-admonition-title-background--caution": "transparent",
    "color-admonition-title-background--warning": "transparent",
    "color-admonition-title-background--danger": "transparent",
    "color-admonition-title-background--attention": "transparent",
    "color-admonition-title-background--error": "transparent",
    "color-admonition-title-background--hint": "transparent",
    "color-admonition-title-background--tip": "transparent",
    "color-admonition-title-background--important": "transparent",
    "color-admonition-title-background--note": "transparent",
    "color-admonition-title-background--seealso": "transparent",
    "color-admonition-title-background--admonition-todo": "transparent",
    "color-table-header-background": "transparent",
    "color-table-border": "var(--sm-rule)",
    "color-card-border": "var(--sm-rule)",
    "color-card-background": "var(--sm-paper)",
    "color-api-background": "transparent",
    "color-api-background-hover": "var(--sm-rule-soft)",
    "color-api-name": "var(--sm-ink)",
    "color-api-pre-name": "var(--sm-ink-2)",
    "color-api-keyword": "var(--sm-ink-2)",
}

html_theme_options = {
    "light_css_variables": furo_variables,
    "dark_css_variables": furo_variables,
    "light_logo": "light_logo.png",
    "dark_logo": "dark_logo.png",
    "sidebar_hide_name": True,
    "source_repository": "https://github.com/hpc-maths/samurai/",
    "source_branch": "main",
    "source_directory": "docs/source/",
    "top_of_page_buttons": ["edit"],
    # A non-empty announcement makes Furo render the full-width bar at the top of
    # the page; _templates/page.html replaces its content with the site header.
    "announcement": "header",
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/hpc-maths/samurai",
            "html": GITHUB_ICON,
            "class": "",
        },
    ],
}

# Code is set in ink, with bold keywords and italic comments; the colours of
# strings and numbers come from samurai.css, the same in light and dark.
pygments_style = "bw"
pygments_dark_style = "bw"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {
#     'collapse_navigation': False,
# }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_css_files = [
    "css/samurai.css",
]

html_js_files = [
    "js/samurai.js",
]

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "Samuraidoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    "pointsize": "11pt",
    # Additional stuff for the LaTeX preamble.
    #
    "preamble": """
    \\fvset{fontsize=\\scriptsize}
    """,
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "samurai.tex", "Samurai Documentation", author, "manual"),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "samurai", "Samurai Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "Samurai",
        "Samurai Documentation",
        author,
        "Samurai developers",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- MyST configuration ------------------------------------------------------

myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "colon_fence",
    "deflist",
    "dollarmath",
    "substitution",
]

# Generate anchors for headings up to level 3, so that `[text](page.md#section)`
# links resolve.
myst_heading_anchors = 3

# -- Options for the linkcheck builder ---------------------------------------

linkcheck_ignore = [
    # Publishers behind doi.org (Elsevier, Springer, SIAM, Cambridge) often
    # answer 403 to automated clients. A DOI is a persistent identifier, so
    # the link stays valid even when the check cannot follow the redirect.
    r"https://doi\.org/",
]

# GitHub builds the heading anchors of a rendered README or Markdown file with
# JavaScript (`#user-content-...`), so linkcheck never finds them in the HTML.
# The pages themselves are still checked.
linkcheck_anchors_ignore_for_url = [r"https://github\.com/"]

# Retry once on a transient network error before reporting a link as broken.
linkcheck_retries = 2
linkcheck_timeout = 30

# -- Doxygen XML for Breathe -------------------------------------------------

docs_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
doxygen_xml_dir = os.path.join(docs_dir, "xml")


def use_placeholder_xml(app, config):
    """Point Breathe to an empty Doxygen index so that the build still completes.

    The placeholder lives in the build directory, not in docs/xml, so that the
    next build runs Doxygen again once it is installed.
    """
    placeholder_dir = os.path.join(app.doctreedir, "doxygen-placeholder-xml")
    os.makedirs(placeholder_dir, exist_ok=True)
    with open(os.path.join(placeholder_dir, "index.xml"), "w", encoding="utf-8") as f:
        f.write(
            '<?xml version="1.0"?>\n'
            '<doxygenindex version="1.9.8"></doxygenindex>\n'
        )
    config.breathe_projects["samurai"] = placeholder_dir


def run_doxygen_if_xml_missing(app, config):
    """Run Doxygen when the XML read by Breathe does not exist yet.

    This gives the same API pages on Read the Docs and in a local build.
    Existing XML is not regenerated: delete docs/xml to refresh it.
    When Doxygen is not installed or fails, the build goes on with a warning
    and the API pages are empty. When Doxygen only reports warnings, the build
    keeps its XML and emits a warning.
    """
    logger = logging.getLogger(__name__)
    xml_dir = os.path.normpath(
        os.path.join(app.confdir, config.breathe_projects["samurai"])
    )
    if os.path.isfile(os.path.join(xml_dir, "index.xml")):
        return
    if xml_dir != doxygen_xml_dir:
        logger.warning(
            "%s has no Doxygen index.xml: the API pages are empty.", xml_dir
        )
        use_placeholder_xml(app, config)
        return
    doxygen = shutil.which("doxygen")
    if doxygen is None:
        logger.warning(
            "doxygen is not installed and %s does not exist: "
            "the API pages are empty. Install doxygen and rebuild.",
            xml_dir,
        )
        use_placeholder_xml(app, config)
        return
    logger.info("running doxygen to generate %s", xml_dir)
    result = subprocess.run(  # nosec B603: fixed argument list, no shell
        [doxygen], cwd=docs_dir, check=False
    )
    if not os.path.isfile(os.path.join(xml_dir, "index.xml")):
        logger.warning(
            "doxygen failed (exit code %d): the API pages are empty.",
            result.returncode,
        )
        use_placeholder_xml(app, config)
    elif result.returncode != 0:
        # The Doxyfile sets WARN_AS_ERROR = FAIL_ON_WARNINGS: Doxygen writes the
        # whole XML, then exits with a non-zero status if it printed a warning.
        # Keep the XML and turn the failure into a Sphinx warning, so that a
        # build with -W fails on this message rather than on every API page.
        logger.warning(
            "doxygen exited with code %d: fix the doxygen warnings printed above.",
            result.returncode,
        )


def setup(app):
    """Generate the Doxygen XML, if it is missing, once the configuration is read."""
    app.connect("config-inited", run_doxygen_if_xml_missing)
