# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import shutil
import subprocess  # nosec B404: runs the doxygen executable found by shutil.which

from sphinx.util import logging

# -- Project information -----------------------------------------------------

project = "samurai"
author = "samurai team"

# Read version from version.txt
with open(os.path.join(os.path.dirname(__file__), "../../version.txt")) as f:
    full_version = f.read().strip()

# The short X.Y version
version = ".".join(full_version.split(".")[:2])
# The full version, including alpha/beta/rc tags
release = full_version

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "breathe",
    "myst_parser",
]

breathe_projects = {"samurai": "../xml"}
breathe_default_project = "samurai"

# Breathe declares the enclosing namespace (`samurai`) once per `doxygenfile`
# directive, and the Sphinx C++ domain reports every declaration after the
# first one as a duplicate. The API pages use `doxygenfile` on several headers
# of the same namespace, so these warnings say nothing about the docs.
suppress_warnings = ["duplicate_declaration.cpp"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# Pages are written in reStructuredText or MyST Markdown. A docname has no
# extension, so converting `page.rst` to `page.md` keeps its URL and its
# toctree entries.
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

rst_epilog = f"""
.. |project| replace:: {project}

.. role:: cpp_code(code)
   :language: c++

"""

# MyST counterpart of the `|project|` substitution in `rst_epilog`:
# write `{{ project }}` in Markdown pages.
myst_substitutions = {"project": project}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "logo": {
        "image_light": "_static/light_logo.png",
        "image_dark": "_static/dark_logo.png",
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/hpc-maths/samurai",
            "icon": "fa-brands fa-square-github",
            "type": "fontawesome",
        },
    ],
    "primary_sidebar_end": ["sidebar-ethical-ads.html"],
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {
#     'collapse_navigation': False,
# }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_css_files = [
    "css/custom.css",
]

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "Samuraidoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    "pointsize": "11pt",
    # Additional stuff for the LaTeX preamble.
    #
    "preamble": """
    \\fvset{fontsize=\\scriptsize}
    """,
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "samurai.tex", "Samurai Documentation", author, "manual"),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "samurai", "Samurai Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "Samurai",
        "Samurai Documentation",
        author,
        "Samurai developers",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- MyST configuration ------------------------------------------------------

myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "colon_fence",
    "deflist",
    "dollarmath",
    "substitution",
]

# Generate anchors for headings up to level 3, so that `[text](page.md#section)`
# links resolve.
myst_heading_anchors = 3

# -- Doxygen XML for Breathe -------------------------------------------------

docs_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
doxygen_xml_dir = os.path.join(docs_dir, "xml")


def use_placeholder_xml(app, config):
    """Point Breathe to an empty Doxygen index so that the build still completes.

    The placeholder lives in the build directory, not in docs/xml, so that the
    next build runs Doxygen again once it is installed.
    """
    placeholder_dir = os.path.join(app.doctreedir, "doxygen-placeholder-xml")
    os.makedirs(placeholder_dir, exist_ok=True)
    with open(os.path.join(placeholder_dir, "index.xml"), "w", encoding="utf-8") as f:
        f.write(
            '<?xml version="1.0"?>\n'
            '<doxygenindex version="1.9.8"></doxygenindex>\n'
        )
    config.breathe_projects["samurai"] = placeholder_dir


def run_doxygen_if_xml_missing(app, config):
    """Run Doxygen when the XML read by Breathe does not exist yet.

    This gives the same API pages on Read the Docs and in a local build.
    Existing XML is not regenerated: delete docs/xml to refresh it.
    When Doxygen is not installed or fails, the build goes on with a warning
    and the API pages are empty.
    """
    logger = logging.getLogger(__name__)
    xml_dir = os.path.normpath(
        os.path.join(app.confdir, config.breathe_projects["samurai"])
    )
    if os.path.isfile(os.path.join(xml_dir, "index.xml")):
        return
    if xml_dir != doxygen_xml_dir:
        logger.warning(
            "%s has no Doxygen index.xml: the API pages are empty.", xml_dir
        )
        use_placeholder_xml(app, config)
        return
    doxygen = shutil.which("doxygen")
    if doxygen is None:
        logger.warning(
            "doxygen is not installed and %s does not exist: "
            "the API pages are empty. Install doxygen and rebuild.",
            xml_dir,
        )
        use_placeholder_xml(app, config)
        return
    logger.info("running doxygen to generate %s", xml_dir)
    result = subprocess.run([doxygen], cwd=docs_dir, check=False)  # nosec B603: fixed argument list, no shell
    if result.returncode != 0 or not os.path.isfile(
        os.path.join(xml_dir, "index.xml")
    ):
        logger.warning(
            "doxygen failed (exit code %d): the API pages are empty.",
            result.returncode,
        )
        use_placeholder_xml(app, config)


def setup(app):
    app.connect("config-inited", run_doxygen_if_xml_missing)
